### ISSUE TITLE
How to disable Swiping drawer to dismiss

### ISSUE THREAD

**Issue by mamin75dev** [aspect-apps/react-native-navigation-drawer-extension#62] opened 2021-09-05 12:13 UTC
Hi,
I am using react-native-navigation and react-native-navigatioin-drawer-extension.

```
"react-native": "^0.62.2",
"react-native-navigation": "^7.0.0",
"react-native-navigation-drawer-extension": "^3.0.0",
```

I want to disable swiping drawer and I try to add `swipeToDismiss: false` to `passProps` and `options` objects. But I didn't get the result that I want. I want that because the drawer make lag and stop in screen when I swiping to dismiss. Please help me to solve this problem.

This is my code to show drawer: 

```
RNNDrawer.showDrawer({
      component: {
        name: Screens.Menu,
        passProps: {
          animationOpenTime: 300,
          animationCloseTime: 300,
          direction: 'right',
          dismissWhenTouchOutside: true,
          fadeOpacity: 0.6,
          swipeToDismiss: false,
          parentComponentId: componentId ? componentId : Screens.Main,
        },
        options: {
          statusBar: statusBar,
        },
      },
      options: {
        swipeToDismiss: false,
      },
    });
```

**Comment by lukebrandonfarrell** [comment] 2021-09-05 15:57
Hey @mamin76dev, 

Please do the following:

1. Upgrade to latest version of react-native-navigation-drawer-extension (4.1.0) and see if it solves your problem
2. If it does not solve your problem, include a video of the problem you are having

Thanks

**Comment by mamin75dev** [comment] 2021-09-06 07:58
> 
> 
> Hey @mamin76dev,
> 
> Please do the following:
> 
>     1. Upgrade to latest version of react-native-navigation-drawer-extension (4.1.0) and see if it solves your problem
> 
>     2. If it does not solve your problem, include a video of the problem you are having
> 
> 
> Thanks

I upgrade the react-nativer-drawer-extension to latest version and the problem has not been resolved yet.
Is there a way I can disable this feature (swiping)? I want to disable it if there is a way!

https://user-images.githubusercontent.com/66959301/132181112-72e299d5-f6e2-41b7-8b03-6d80ac07bc0d.mp4

**Comment by CursedWizard** [comment] 2021-09-06 09:03
@mamin75dev, on the video you still have some older version, because the drawer doesn't jump like that on the latest one. Are you sure you upgraded it?

**Comment by mamin75dev** [comment] 2021-09-06 09:35
> 
> 
> @mamin75dev, on the video you still have some older version, because the drawer doesn't jump like that on the latest one. Are you sure you upgraded it?

Yes, I upgrade it.
Finally, I found the issue! I wrap a list in the menu!!! and this list causing this issue!! If I delete this list everything is ok. But I want this. (both of the flatlist and scrollview not sorking)
Is there any solution to fix this?

**Comment by CursedWizard** [comment] 2021-09-07 11:36
@mamin75dev, yeah, there's a bug with ScrollView and other views that are based on it. The problem is that ScrollView claims the touch responsiveness from the parent responder in the drawer, so touch events in the drawer stop being called and thus properly handled. That's a reason why the drawer gets stuck on dragging.
I couldn't find a solid solution to this problem yet. But I guess creating a wrapper around ScrollView, that would toggle `scrollEnabled` property on / off is the way. I tried this approach though and it didn't seem responsive enough to me.

**Comment by lukebrandonfarrell** [comment] 2021-09-07 14:20
@CursedWizard Do you know if with current implementation we can disable swipe to close? @mamin75dev are you using `SideMenuView`?

**Comment by mamin75dev** [comment] 2021-09-07 19:20
> @CursedWizard Do you know if with current implementation we can disable swipe to close? @mamin75dev are you using `SideMenuView`?

Yes, I am using SideMenuView. And also test a simple view. 
But I didn't find any solution in here and even in the stackoverflow.
And finally I forced to edit a RNNDrawer.js file in the package and comment all swipe listeners ... :)

**Comment by lukebrandonfarrell** [comment] 2021-09-10 09:51
Closed by #63

**Closed by lukebrandonfarrell** 2021-09-10 09:51 UTC

**Comment by CursedWizard** [comment] 2021-09-10 11:17
Just wanted to clarify about my commit. There are two props added: `disableDragging`  and `disableSwiping`. In order to avoid the bug @mamin75dev experienced, setting `disableDragging` to true should be enough. It doesn't effect swiping gesture, so it still should close the drawer if swiped from the edge. But you should add enough padding to the wrapper view though for this to work. I tried it with `SideMenuView` too and it worked good for me, but I still would recommend setting some padding.

If you want to turn off any gesture interaction whatsoever, you also can set `disableSwiping` to true. But don't use this prop without `disableDragging` set to true, because it wouldn't make sense and would work weirdly.

@mamin75dev, could you please upgrade to the latest version and verify, that it worked for you?

Also, I wouldn't be so fast about closing this one, since my commit doesn't fix the issue but only adds an option to avoid it.

**Comment by mamin75dev** [comment] 2021-09-20 10:21
> 
> 
> Just wanted to clarify about my commit. There are two props added: `disableDragging` and `disableSwiping`. In order to avoid the bug @mamin75dev experienced, setting `disableDragging` to true should be enough. It doesn't effect swiping gesture, so it still should close the drawer if swiped from the edge. But you should add enough padding to the wrapper view though for this to work. I tried it with `SideMenuView` too and it worked good for me, but I still would recommend setting some padding.
> 
> If you want to turn off any gesture interaction whatsoever, you also can set `disableSwiping` to true. But don't use this prop without `disableDragging` set to true, because it wouldn't make sense and would work weirdly.
> 
> @mamin75dev, could you please upgrade to the latest version and verify, that it worked for you?
> 
> Also, @lukebrandonfarrell, I wouldn't be so fast about closing this one, since my commit doesn't fix the issue but only adds an option to avoid it.

Thanks for your commit! Its working!

**Comment by CursedWizard** [comment] 2021-09-20 22:41
@mamin75dev, good. By the way, check out my [bottom sheet library](https://github.com/CursedWizard/react-native-navigation-bottom-sheet) I also built for RNN. Could be useful.
