### ISSUE TITLE
Closing drawer while pushing a screen causes the drawer to disappear instead of sliding away 

### ISSUE THREAD

**Issue by ahmedXabdeen** [aspect-apps/react-native-navigation-drawer-extension#32] opened 2020-10-10 14:00 UTC
First of all thanks for such a useful package!

I've implemented a drawer component that has a list of touchable screen names for the user to navigate the app. Naturally, when navigating to another screen you would want the drawer to close. What happens is pushing another screen while closing the drawer causes the drawer to disappear immediately from the view instead of sliding away. And the whole feel to it isn't pleasant.

I'm using this package in an app that is soon to be launched, so I came up with a workaround that is, delaying the push action for the same amount of time that is set for the `animationCloseTime` prop when showing the drawer component.

I'm not sure if there's anything to do on this package's part. Please let me know if you have any ideas for a hotfix, I'm willing to help!

**Comment by rodriigovieira** [comment] 2020-11-03 03:48
Hey @ahmedXabdeen!

I was not able to reproduce the issue neither on Android nor iOS on a fresh project. I called `RNNDrawer.dismissDrawer()` and then `Navigation.push(...)` and it animated correctly, even if I place the method after pushing the new screen.

![Nov-03-2020 00-44-30](https://user-images.githubusercontent.com/7014073/97948087-35bb2f80-1d6e-11eb-8266-dca80f061213.gif)
![Nov-03-2020 00-43-52](https://user-images.githubusercontent.com/7014073/97948088-381d8980-1d6e-11eb-8a6f-284894dcbb4b.gif)

How could I replicate this issue?

**Comment by lukebrandonfarrell** [comment] 2020-11-03 16:00
@ahmedXabdeen Upgrade to the latest version of React Native Navigation and this should be fixed. We can't replicate this

**Closed by lukebrandonfarrell** 2020-11-03 16:00 UTC

**Comment by Desintegrator** [comment] 2022-12-27 22:39
same here
